language: go
go:
  - "1.12"
services:
  - docker
before_install:
  - docker pull golang:1.12.7-alpine
  - docker pull k8s.gcr.io/debian-base:v1.0.0

script:
  - go build -o _output/main cmd/disk/main.go
