language: go
go:
  - "1.12"
services:
  - docker
before_install:
  - docker pull golang:1.12.7-alpine
  - docker pull k8s.gcr.io/debian-base:v1.0.0

install:
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure -vendor-only
script:
  - make disk-container
