apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clone-of-pvc-1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  dataSource:
    kind: PersistentVolumeClaim
    name: pvc-example
  storageClassName: csi-qingcloud